import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/AuthProvider/Provider";
import NavBar from "./components/NavBar/NavBar";
import Footer from "./components/Footer/Footer";
import { DataContext } from "@/Context/AppContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html
			lang="en"
			data-theme="dim"
		>
			<body className={`${inter.className} `}>
				<Provider>
					<main className="flex flex-col justify-between h-screen">
						<DataContext>
							<NavBar />
							<section className="flex-1">{children}</section>
							<Footer />
						</DataContext>
					</main>
				</Provider>
			</body>
		</html>
	);
}
